export const ON_TEXT_UPDATED = 'on text updated'
export const ON_TASKS_UPDATED = 'on tasks updated'
export const ON_TASK_ADDED = 'on task added'
export const ON_TASK_REMOVED = 'on task removed'
export const ON_TASK_TOGGLED = 'on task toggled'
